main: com.cavetale.territory.TerritoryPlugin

name: Territory
version: 0.1
description: Create territories in the mining world.
api-version: 1.19

author: StarTux
website: https://github.com/StarTux/Territory

depend: [Core]
softdepend: [Decorator, Structure]

commands:

  territory:
    description: Admin command
    usage: |-
      /territory here - Current location info

permissions:

  territory.territory:
    description: Use the /territory command (admin)

  territory.mine:
    description: Use the /mine command (players)